# CONFIGURACIÓN DE CLOUDFLARE PAGES - WRANGLER

name = "jopes"
compatibility_date = "2026-05-19"
main = "src/index.js"

# Despliegue moderno de archivos estáticos (Wrangler v3+)
[assets]
directory = "./"

routes = [
  { pattern = "student-balance-planner.tech", custom_domain = true }
]


[[kv_namespaces]]
binding = "JOSEPH_DB"
id = "f385cd69f4b3420d9261f531913bdb2a"
